<?php
    header('Access-Control-Allow-Origin: *');
    header('Content-Type: application/json; charset=utf-8');
    $informacion = new stdClass();

    $informacion->imgenEmpresa = "Logo";
    $informacion->menu = ["Home", "About", "Events", "Contact"];
    $informacion->titulo = "Parallax Website";
    $informacion->secion = "Parallax Scrolling Website";
    $informacion->parrafo = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo officiis tempora fuga debitis perferendis soluta dicta natus mollitia, quas minima totam, voluptatum consequatur modi quam quasi quis laboriosam eum? Fugiat! Odio laudantium eum, ab dolore voluptatibus dolorum voluptates dolor necessitatibus distinctio quidem adipisci, praesentium alias magni quisquam reprehenderit soluta cupiditate veritatis sapiente placeat dolores! Excepturi incidunt repellendus non perferendis eius! Ad, nisi quisquam provident esse tempore cumque non eius, voluptatem error repudiandae recusandae maiores aut voluptate cupiditate officia corporis quae, quo id neque nihil earum placeat voluptas aliquid. Quia, perferendis. Sequi porro quas totam ea rerum aliquid error a at suscipit inventore impedit, eum vero omnis tempora velit odit voluptatum similique excepturi aspernatur quia voluptates. Corrupti pariatur distinctio delectus architecto. Ea consequatur corporis quis natus quisquam. Voluptas doloremque reprehenderit corporis! Asperiores tenetur harum, voluptatum tempora voluptatibus autem sapiente, expedita libero quia nisi amet quam ab minus doloremque exercitationem eum distinctio. Nesciunt quidem ratione sint dolorum magni! Nobis modi molestias, eos aut culpa perferendis ipsam odio suscipit velit nulla, cum ullam porro! Iusto autem rerum pariatur totam molestias neque quis ipsum! Illo consectetur perspiciatis consequatur corrupti cumque qui sunt doloribus dolorem, eaque voluptate laborum neque dicta quaerat porro eligendi dolor, ad aliquid cum error magni est deleniti ut sint. Fugiat, repellat. Modi facere eum voluptas minus enim, placeat numquam velit minima cumque architecto blanditiis, aliquam officiis. Eius dignissimos repudiandae architecto, quae enim doloremque tempore qui quisquam earum, neque assumenda quas in. Aliquid commodi error magnam, distinctio at ad debitis repellendus quas id, similique impedit. Maiores voluptatibus sapiente consequuntur quasi! Facilis natus quidem quos vero amet corporis nihil rerum iste dolor asperiores. Error dolorum fugit debitis praesentium iste voluptatem facere culpa rerum consectetur aut inventore assumenda velit dolor vero, nam reprehenderit repellendus? Officiis modi cum quos autem ipsam, provident voluptatem aliquid ratione! Ullam animi rerum molestiae nesciunt quam, earum cupiditate libero magni ipsam laborum doloremque culpa vero rem. Maiores iusto incidunt, mollitia, consequatur quam voluptates nobis, vero libero fugit quos debitis. Debitis! Fugiat enim, porro, deleniti quidem deserunt";
    $informacion->servidor = $_SERVER["HTTP_HOST"];
    
    echo json_encode($informacion, JSON_PRETTY_PRINT);
?>